import type { Series } from '../lib/types'

/**
 * CITED — real executive statements, hand-entered with their sources.
 *
 * This replaced the last invented curve on the dashboard. There is still no
 * *feed* for "share of code written by AI" — but Google has stated the figure
 * for its own new code on four dated occasions, and four dated points from one
 * named company beat eleven invented points about "large orgs" in general.
 *
 * Every point's quote:
 *
 *  2024-10-29  "Today, more than a quarter of all new code at Google is
 *              generated by AI, then reviewed and accepted by engineers."
 *              — Sundar Pichai, Alphabet Q3 2024 earnings call
 *  2025-04-24  "well over 30%" — Alphabet Q1 2025 earnings call
 *  2025-10-15  ~50% — "up from 50% last fall", per the April 2026 reporting
 *              (secondhand; dated approximately to the fall reference)
 *  2026-04-24  75% "of all new code at Google is now AI-generated and approved
 *              by engineers" — Alphabet Q1 2026 earnings call, as reported by
 *              Semafor, Fast Company and DevOps.com
 *
 * Caveats, stated where the chart shows them: one company; "generated then
 * reviewed" is Google's definition, not an audit; the 50% point is secondhand.
 * Values are shares (0..1) of NEW code, matching the doom model's input.
 */
export const googleAiCodeShare: Series = {
  id: 'aicode-google',
  label: 'New code at Google that is AI-generated',
  unit: 'share',
  provenance: 'cited',
  source: 'Alphabet earnings-call statements, 2024\u20132026 (Pichai)',
  sourceUrl: 'https://www.semafor.com/article/04/24/2026/google-ceo-says-75-of-companys-new-code-is-ai-generated',
  points: [
    { t: '2024-10-29', v: 0.25 },
    { t: '2025-04-24', v: 0.30 },
    { t: '2025-10-15', v: 0.50 },
    { t: '2026-04-24', v: 0.75 },
  ],
}
